about/urls.py
from django.urls import path
from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='posts_list'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/follow/', views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='posts',
        blank=True, null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField('Изображение', upload_to='posts/', blank=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(verbose_name='Комментарий', null=True, blank=True)
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_list')
        ]

posts/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text', 'image']
        help_texts = {
            'group': 'Если укажешь группу, мы будем благодарны',
            'text': 'Напишите пост',
            'image': 'якартинко'
            }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {'text': Textarea(attrs={'cols': 80, 'rows': 5})}

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.cache import cache_page

from posts.models import Post, Group, User, Follow
from posts.forms import PostForm, CommentForm


@cache_page(20)
def index(request):
    posts = Post.objects.order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author).all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count_post = post_list.count()
    follower = Follow.objects.filter(user=author)
    following = Follow.objects.filter(author=author)
    context = {
        'profile': author,
        'page_obj': page_obj,
        'paginator': paginator,
        'count_post': count_post,
        'follower': follower,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_list = Post.objects.filter(author=author).all()
    count_post = post_list.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'count_post': count_post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {
        'groups': groups,
        'form': form
    }
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    new_post = form.save(commit=False)
    new_post.author = request.user
    form.save()
    return redirect('posts:profile', username=new_post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    groups = Group.objects.all()
    is_edit = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=is_edit
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': is_edit,
        'groups': groups,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'profile': profile,
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/comments.html', context)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    follower = request.user
    following = get_object_or_404(User, username=username)
    if following == request.user:
        return redirect('posts:profile', username=username)
    author_list, created = Follow.objects.get_or_create(
        user=follower,
        author=following
    )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follower = request.user
    following = get_object_or_404(User, username=username)
    author_list = Follow.objects.filter(user=follower, author=following)
    if not username == follower.username and author_list:
        author_list.delete()
    return redirect('posts:profile', username=username)

templates/posts/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p> {{ comment.text }} </p>
    </div>
  </div>
{% endfor %}

templates/posts/create_post.html
{% extends 'base.html' %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}
              </div>
              <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger">*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                      {% if is_edit %}
                        {{ post.text }}
                      {% endif %}
                    </textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form__group row my-3 p-3">
                    <label for="id_group">
                      Group
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>--------</option>
                      {% for group in groups %}
                        <option value={{ group.id }}>{{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form__group row my-3 p-3">
                    {% if is_edit %}
                      <label for="id_image">Изображение</label>
                      На данный момент
                      <a href="/media/{{ post.image }}">{{ post.image }}</a>
                      <label for="image-clear_id">Очистить
                        <input type="checkbox" name="image-clear" id="image-clear_id">
                      </label>
                      <br>
                      Изменить
                      <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                    {% else %}
                      <label for="id_image">Изображение</label>
                      <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                    {% endif %}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
{% endblock %}
<!--- <body>
   <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if edit_post %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}
              </div>
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form__group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                </textarea>
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Group
                </label>
                <select name="group" class="form-control" id="id_group">
                   <option value="{{ form.group }}">{{ form.group }}</option>
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if edit_post %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </main>
  </body>--->

templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Последние обноваления избранных авторов{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        {% include 'includes/switcher.html' %}
        <div class="container py-4">
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
              {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
          </article>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
        </div>
      </div>
    </main>
  </body>
{% endblock %}

templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>
          Записи сообщества "{{ group.title }}"
        </h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
    </main>
  </body>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>
          Последние обновления на сайте
        </h1>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
          </article>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
    </main>
  </body>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
              {% if post.group %}
                <li class="list-group-item">
                  Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
                </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ count_post }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              Редактировать запись
            </a>
            {% endif %}

            {% include 'posts/comments.html' %}
          </article>
        </div>
      </div>
    </main>
  </body>
{% endblock %}

templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>Все посты пользователя {{ profile.first_name }} {{ profile.last_name }} </h1>
        <h3>Всего постов: {{ count_post }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' profile %}" role="button">
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' profile %}" role="button">
            Подписаться
          </a>
        {% endif %}
        <article>
          {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <p>{{ post.text }}</p>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
            </article>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
        {% include 'includes/paginator.html' %}
      </div>
    </main>
  </body>
{% endblock %}